# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class CRMBA(Ontology):

    def __init__(self) -> None:
        super().__init__('CRMba version 1.4', 'crmba', 'https://ontome.net/ns/crmba/')

    # Classes
    B1_Built_Work = Resource("crmba:B1", "Built Work", class_uri="owl:Class")
    B2_Morphological_Building_Section = Resource("crmba:B2", "Morphological Building Section", class_uri="owl:Class")
    B3_Filled_Morphological_Building_Section = Resource("crmba:B3", "Filled Morphological Building Section", class_uri="owl:Class")
    B4_Empty_Morphological_Building_Section = Resource("crmba:B4", "Empty Morphological Building Section", class_uri="owl:Class")

    # Properties
    BP1_Is_Section_Of = Resource("crmba:BP1", "is section of", class_uri="owl:Property")
