# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class LRMOO(Ontology):

    def __init__(self) -> None:
        super().__init__('LRMoo 1.0', 'lrmoo', 'http://iflastandards.info/ns/lrm/lrmoo/')

    # Classes
    F2_Expression = Resource("lrmoo:F2", "Expression", class_uri="owl:Class")
    F5_Item = Resource("lrmoo:F5", "Item", class_uri="owl:Class")
    F18_Serial_Work = Resource("lrmoo:F18", "Serial Work", class_uri="owl:Class")
    F28_Expression_Creation = Resource("lrmoo:F28", "Expression Creation", class_uri="owl:Class")
    F31_Performance = Resource("lrmoo:F31", "Performance", class_uri="owl:Class")

    # Properties
