# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class MAR(Ontology):

    def __init__(self) -> None:
        super().__init__('Maritime history ongoing', 'mar', 'https://ontome.net/ns/maritime-history/')

    # Classes
    C2_Ship = Resource("mar:C2", "Ship", class_uri="owl:Class")
    C1_Ship_Voyage = Resource("mar:C1", "Ship Voyage", class_uri="owl:Class")
    C3_Ship_Type = Resource("mar:C3", "Ship Type", class_uri="owl:Class")
    C4_Shipyard = Resource("mar:C4", "Shipyard", class_uri="owl:Class")
    C5_Economic_Good = Resource("mar:C5", "Economic good", class_uri="owl:Class")
    C6_Transport = Resource("mar:C6", "Transport", class_uri="owl:Class")
    C7_Stopover = Resource("mar:C7", "Stopover", class_uri="owl:Class")
    C8_Voc_Chamber = Resource("mar:C8", "VOC Chamber", class_uri="owl:Class")
    C12_Shipbuilding = Resource("mar:C12", "Shipbuilding", class_uri="owl:Class")

    # Properties
    P1_Had_Departure_Place = Resource("mar:P1", "had departure place", class_uri="owl:Property")
    P2_Had_Arrival_Place = Resource("mar:P2", "had arrival place", class_uri="owl:Property")
    P6_Has_Ship_Type = Resource("mar:P6", "has ship type", class_uri="owl:Property")
    P3_Was_Carried_Out_By = Resource("mar:P3", "was carried out by", class_uri="owl:Property")
    P4_Took_Place_At = Resource("mar:P4", "took place at", class_uri="owl:Property")
    P5_Was_Part_Of = Resource("mar:P5", "was part of", class_uri="owl:Property")
    P7_Has_Built = Resource("mar:P7", "has built", class_uri="owl:Property")
    P8_Carried_Out_By = Resource("mar:P8", "carried out by", class_uri="owl:Property")
    P9_Is_Carried_Out_In_The_Context_Of = Resource("mar:P9", "is carried out in the context of", class_uri="owl:Property")
    P10_Has_Set_Up = Resource("mar:P10", "has set up", class_uri="owl:Property")
    P11_Carried = Resource("mar:P11", "carried", class_uri="owl:Property")
    P12_Participated_In = Resource("mar:P12", "participated in", class_uri="owl:Property")
