# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class SDH_SLS(Ontology):

    def __init__(self) -> None:
        super().__init__('SDHSS Extension - Human and Social Life, Specific Aspects (v1.0)', 'sdh-sls', 'https://sdhss.org/ontology/social-life-specific/')

    # Classes
    C1_Taking_Care_Of_A_Person = Resource("sdh-sls:C1", "Taking Care of a Person", class_uri="owl:Class")
    C2_Attending_A_School = Resource("sdh-sls:C2", "Attending a School", class_uri="owl:Class")
    C3_Taking_Care_Of_A_Person_Type = Resource("sdh-sls:C3", "Taking Care of a Person Type", class_uri="owl:Class")
    C4_Attending_A_School_Type = Resource("sdh-sls:C4", "Attending a School Type", class_uri="owl:Class")
    C6_Study = Resource("sdh-sls:C6", "Study", class_uri="owl:Class")
    C9_Academic_Discipline = Resource("sdh-sls:C9", "Academic Discipline", class_uri="owl:Class")
    C7_Obtaining_A_Study_Title = Resource("sdh-sls:C7", "Obtaining a Study Title", class_uri="owl:Class")
    C8_Study_Title = Resource("sdh-sls:C8", "Study title", class_uri="owl:Class")
    C10_Academic_Chair = Resource("sdh-sls:C10", "Academic Chair", class_uri="owl:Class")
    C5_Teaching = Resource("sdh-sls:C5", "Teaching", class_uri="owl:Class")
    C11_Academic_Position = Resource("sdh-sls:C11", "Academic Position", class_uri="owl:Class")

    # Properties
    P1_Take_Care_Of = Resource("sdh-sls:P1", "take care of", class_uri="owl:Property")
    P2_Has_Caretaker = Resource("sdh-sls:P2", "has caretaker", class_uri="owl:Property")
    P3_Concerned_Person = Resource("sdh-sls:P3", "concerned person", class_uri="owl:Property")
    P4_Concerned_School = Resource("sdh-sls:P4", "concerned school", class_uri="owl:Property")
    P5_Has_Taking_Care_Type = Resource("sdh-sls:P5", "has taking care type", class_uri="owl:Property")
    P6_Has_Attending_A_School_Type = Resource("sdh-sls:P6", "has attending a school type", class_uri="owl:Property")
    P7_Is_Study_At = Resource("sdh-sls:P7", "is study at", class_uri="owl:Property")
    P8_Is_The_Study_By = Resource("sdh-sls:P8", "is the study by", class_uri="owl:Property")
    P18_Is_Study_Of = Resource("sdh-sls:P18", "is study of", class_uri="owl:Property")
    P9_Was_Obtained_By = Resource("sdh-sls:P9", "was obtained by", class_uri="owl:Property")
    P10_Is_Obtention_Of = Resource("sdh-sls:P10", "is obtention of", class_uri="owl:Property")
    P11_Has_Academic_Supervisor = Resource("sdh-sls:P11", "has academic supervisor", class_uri="owl:Property")
    P17_Is_Delivered_By = Resource("sdh-sls:P17", "is delivered by", class_uri="owl:Property")
    P19_Is_Obtained_At = Resource("sdh-sls:P19", "is obtained at", class_uri="owl:Property")
    P16_Has_As_Disciplinary_Area = Resource("sdh-sls:P16", "has as disciplinary area", class_uri="owl:Property")
    P12_Concerns = Resource("sdh-sls:P12", "concerns", class_uri="owl:Property")
    P13_Is_Carried_Out_By = Resource("sdh-sls:P13", "is carried out by", class_uri="owl:Property")
    P14_Carried_Out_At = Resource("sdh-sls:P14", "carried out at", class_uri="owl:Property")
    P15_Has_Rank = Resource("sdh-sls:P15", "has rank", class_uri="owl:Property")
