# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class SDH_ARCH(Ontology):

    def __init__(self) -> None:
        super().__init__('SDHSS Extension - Archaeology', 'sdh-arch', 'https://sdhss.org/ontology/archaeology/')

    # Classes
    C1_Archaeological_Excavation_Type = Resource("sdh-arch:C1", "Archaeological Excavation Type", class_uri="owl:Class")
    C2_Excavation_Process_Unit_Type = Resource("sdh-arch:C2", "Excavation Process Unit Type", class_uri="owl:Class")

    # Properties
    P1_Has_Archeological_Excavation_Type = Resource("sdh-arch:P1", "has archeological excavation type", class_uri="owl:Property")
    P2_Has_Excavation_Process_Unit_Type = Resource("sdh-arch:P2", "has excavation process unit type", class_uri="owl:Property")
    P3_Overlies = Resource("sdh-arch:P3", "overlies", class_uri="owl:Property")
    P4_Cuts = Resource("sdh-arch:P4", "cuts", class_uri="owl:Property")
