# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class SDH_INFO(Ontology):

    def __init__(self) -> None:
        super().__init__('SDHSS for Sources Information and Metadata (v1.0)', 'sdh-info', 'https://sdhss.org/ontology/sources-information-metadata/')

    # Classes
    C2_Expression_Portion = Resource("sdh-info:C2", "Expression Portion", class_uri="owl:Class")
    C3_Expression_Portion_Type = Resource("sdh-info:C3", "Expression Portion Type", class_uri="owl:Class")
    C4_Asserted_Actor_S_Role = Resource("sdh-info:C4", "Asserted Actor's Role", class_uri="owl:Class")
    C5_Bibliographic_Citation = Resource("sdh-info:C5", "Bibliographic Citation", class_uri="owl:Class")
    C6_Citation_Style = Resource("sdh-info:C6", "Citation Style", class_uri="owl:Class")
    C19_Item_Collection = Resource("sdh-info:C19", "Item Collection", class_uri="owl:Class")
    C1_Expression_Publication_Event = Resource("sdh-info:C1", "Expression Publication Event", class_uri="owl:Class")
    C11_Expression_Portion_Classification = Resource("sdh-info:C11", "Expression Portion Classification", class_uri="owl:Class")
    C12_Subject = Resource("sdh-info:C12", "Subject", class_uri="owl:Class")
    C7_Propositional_Datation = Resource("sdh-info:C7", "Propositional Datation", class_uri="owl:Class")
    C8_Datation_Type = Resource("sdh-info:C8", "Datation Type", class_uri="owl:Class")
    C9_Quantifiable_Component = Resource("sdh-info:C9", "Quantifiable Component", class_uri="owl:Class")
    C10_Quantifiable_Component_Type = Resource("sdh-info:C10", "Quantifiable Component Type", class_uri="owl:Class")

    # Properties
    P4_Is_Part_Of = Resource("sdh-info:P4", "is part of", class_uri="owl:Property")
    P5_Has_Expression_Portion_Type = Resource("sdh-info:P5", "has expression portion type", class_uri="owl:Property")
    P6_Is_Role_Of = Resource("sdh-info:P6", "is role of", class_uri="owl:Property")
    P7_Is_Asserted_By = Resource("sdh-info:P7", "is asserted by", class_uri="owl:Property")
    P8_Is_Qualified_By = Resource("sdh-info:P8", "is qualified by", class_uri="owl:Property")
    P9_Is_In_The_Role_Of = Resource("sdh-info:P9", "is in the role of", class_uri="owl:Property")
    P10_Has_Style = Resource("sdh-info:P10", "has style", class_uri="owl:Property")
    P11_Has_Issue = Resource("sdh-info:P11", "has issue", class_uri="owl:Property")
    P16_Has_Main_Language = Resource("sdh-info:P16", "has main language", class_uri="owl:Property")
    P1_Used_Specific_Expression = Resource("sdh-info:P1", "used specific expression", class_uri="owl:Property")
    P2_Created_Manifestation = Resource("sdh-info:P2", "created manifestation", class_uri="owl:Property")
    P3_Published_The_Work_Of = Resource("sdh-info:P3", "published the work of", class_uri="owl:Property")
    P18_Classifies_With = Resource("sdh-info:P18", "classifies with", class_uri="owl:Property")
    P19_Used_Carrier = Resource("sdh-info:P19", "used carrier", class_uri="owl:Property")
    P12_Has_Datation_Value = Resource("sdh-info:P12", "has datation value", class_uri="owl:Property")
    P13_Has_Datation_Type = Resource("sdh-info:P13", "has datation type", class_uri="owl:Property")
    P14_Has_Component_Dimension = Resource("sdh-info:P14", "has component dimension", class_uri="owl:Property")
    P15_Has_Quantifiable_Component_Type = Resource("sdh-info:P15", "has quantifiable component type", class_uri="owl:Property")
