queries:
  - name: Delete all data
    query: |
      CLEAR ALL
  - name: List all graphs
    query: |
      SELECT DISTINCT ?graph
      WHERE {
        GRAPH ?graph { 
          ?s ?p ?o .
        }
      }

prefixes:
  - short: rdf
    long: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  - short: rdfs
    long: http://www.w3.org/2000/01/rdf-schema#
  - short: xsd
    long: http://www.w3.org/2001/XMLSchema#
  - short: owl
    long: http://www.w3.org/2002/07/owl#
  - short: sh
    long: http://www.w3.org/ns/shacl#
  - short: crm
    long: http://www.cidoc-crm.org/cidoc-crm/
  - short: sdh
    long: https://sdhss.org/ontology/core/
  - short: sdh-shortcut
    long: https://sdhss.org/ontology/shortcuts/
  - short: sdh-shacl
    long: https://sdhss.org/shacl/profiles/
  - short: ontome
    long: https://ontome.net/ontology/