data_bundles:
- base_uri: http://geovistory.org/resource/
  endpoint_technology: GraphDB
  endpoint_url: https://sparql-gdb.geovistory.org/solidamin
  graph_data_uri: http://geovistory.org/resource/rf_distribution_data
  graph_metadata_uri: null
  graph_model_uri: http://geovistory.org/resource/rf_distribution_shacl
  model_framework: SHACL
  name: Refuge Huguenot
  password: cX5$Eo@NE#@&qz#A
  prop_comment_uri: rdfs:comment
  prop_label_uri: rdfs:label
  prop_type_uri: rdf:type
  username: orianemanigault
- base_uri: http://geovistory.org/resource/
  endpoint_technology: GraphDB
  endpoint_url: https://sparql-gdb.geovistory.org/solidamin
  graph_data_uri: http://geovistory.org/resource/antoine_court_data
  graph_metadata_uri: null
  graph_model_uri: http://geovistory.org/resource/antoine_court_shacl
  model_framework: SHACL
  name: Antoine Court
  password: cX5$Eo@NE#@&qz#A
  prop_comment_uri: rdfs:comment
  prop_label_uri: rdfs:label
  prop_type_uri: rdf:type
  username: orianemanigault
- base_uri: http://localhost/plan-menu/entity/
  endpoint_technology: Fuseki
  endpoint_url: http://localhost:3030/plan-menu
  graph_data_uri: base:data
  graph_metadata_uri: base:metadata
  graph_model_uri: base:model
  model_framework: SHACL
  name: Plan Menu
  password: QRTJS9Vcvim51rV
  prop_comment_uri: rdfs:comment
  prop_label_uri: rdfs:label
  prop_type_uri: rdf:type
  username: admin
default_data_bundle: plan-menu
prefixes:
- long: http://www.w3.org/1999/02/22-rdf-syntax-ns#
  short: rdf
- long: http://www.w3.org/2000/01/rdf-schema#
  short: rdfs
- long: http://www.w3.org/2001/XMLSchema#
  short: xsd
- long: http://www.w3.org/2002/07/owl#
  short: owl
- long: http://www.w3.org/ns/shacl#
  short: sh
- long: http://www.cidoc-crm.org/cidoc-crm/
  short: crm
- long: https://ontome.net/ontology/
  short: ontome
- long: https://www.iflastandards.info/fr/frbr/frbroo#
  short: frbroo
- long: https://sdhss.org/ontology/crm-supplement/
  short: crm-sup
- long: https://sdhss.org/ontology/core/
  short: sdh
- long: https://sdhss.org/ontology/shortcuts/
  short: sdh-shortcut
- long: https://sdhss.org/ontology/social-life-core/
  short: sdh-slc
- long: https://sdhss.org/shacl/profiles/
  short: sdh-shacl
- long: https://sdhss.org/ontology/sources-information/
  short: sdh-info
- long: http://iflastandards.info/ns/lrm/lrmoo/
  short: lrmoo
- long: http://localhost/plan-menu/model/
  short: menu
sparql_queries:
- - Default
  - "SELECT * \nWHERE {\n    ?s ?p ?o .\n}\nLIMIT 10"
- - List named graphs
  - "SELECT DISTINCT ?graph\nWHERE {\n    GRAPH ?graph {\n        ?s ?p ?o .\n   \
    \ }\n}\n"
- - Delete all triples from endpoint
  - CLEAR ALL
