from .graph import Graph
from .model import Model
from .ontology import Ontology
from .prefix import Prefix
from .prefixes import Prefixes
from .property import Property
from .resource import Resource
from .sparql import Sparql
from .statement import Statement