# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class ANY_A(Ontology):

    def __init__(self) -> None:
        super().__init__('ANY-ARTEFACT-V.1 ongoing', 'any-a', 'https://ontome.net/ns/any-artefact-v-1/')

    # Classes
    A1_Endurant_A1_Endurant = Resource("any-a:A1_Endurant", "A1_Endurant", class_uri="owl:Class")
    A3_Quality_A3_Quality = Resource("any-a:A3_Quality", "A3_Quality", class_uri="owl:Class")
    A2_Perdurant_A2_Perdurant = Resource("any-a:A2_Perdurant", "A2_Perdurant", class_uri="owl:Class")
    A22111_A_Procedure_A22111_A_Procedure = Resource("any-a:A22111_A-Procedure", "A22111_A-Procedure", class_uri="owl:Class")
    A2224_End_of_activity_A2224_End_Of_Activity = Resource("any-a:A2224_End_of_activity", "A2224_End_of_activity", class_uri="owl:Class")
    A2225_Patrimonalization_A2225_Patrimonalization = Resource("any-a:A2225_Patrimonalization", "A2225_Patrimonalization", class_uri="owl:Class")
    A0_Any_Artefact_Entity_A0_Any_Artefact_Entity = Resource("any-a:A0_Any_Artefact_Entity", "A0_Any_Artefact_Entity", class_uri="owl:Class")

    # Properties
