# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class CRMARC(Ontology):

    def __init__(self) -> None:
        super().__init__('CRMarchaeo version 2.1.1', 'crmarc', 'http://www.cidoc-crm.org/extensions/crmarchaeo/')

    # Classes
    A1_Excavation_Process_Unit = Resource("crmarc:A1", "Excavation Process Unit", class_uri="owl:Class")
    A2_Stratigraphic_Volume_Unit = Resource("crmarc:A2", "Stratigraphic Volume Unit", class_uri="owl:Class")
    A3_Stratigraphic_Interface = Resource("crmarc:A3", "Stratigraphic Interface", class_uri="owl:Class")
    A7_Embedding = Resource("crmarc:A7", "Embedding", class_uri="owl:Class")
    A9_Archaeological_Excavation = Resource("crmarc:A9", "Archaeological Excavation", class_uri="owl:Class")

    # Properties
    AP5_Removed_Part_Or_All_Of = Resource("crmarc:AP5", "removed part or all of", class_uri="owl:Property")
    AP18_Is_Embedding_Of = Resource("crmarc:AP18", "is embedding of", class_uri="owl:Property")
    AP19_Is_Embedding_In = Resource("crmarc:AP19", "is embedding in", class_uri="owl:Property")
    AP3_Excavated = Resource("crmarc:AP3", "excavated", class_uri="owl:Property")
    AP25_Occurs_During = Resource("crmarc:AP25", "occurs during", class_uri="owl:Property")
