# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class CRMINF(Ontology):

    def __init__(self) -> None:
        super().__init__('CRMinf version 1.0', 'crminf', 'http://www.cidoc-crm.org/extensions/crminf/')

    # Classes
    I2_Belief = Resource("crminf:I2", "Belief", class_uri="owl:Class")
    I3_Inference_Logic = Resource("crminf:I3", "Inference Logic", class_uri="owl:Class")
    I4_Proposition_Set = Resource("crminf:I4", "Proposition Set", class_uri="owl:Class")
    I5_Inference_Making = Resource("crminf:I5", "Inference Making", class_uri="owl:Class")
    I6_Belief_Value = Resource("crminf:I6", "Belief Value", class_uri="owl:Class")

    # Properties
    J1_Used_As_Premise = Resource("crminf:J1", "used as premise", class_uri="owl:Property")
    J2_Concluded_That = Resource("crminf:J2", "concluded that", class_uri="owl:Property")
    J3_Applies = Resource("crminf:J3", "applies", class_uri="owl:Property")
    J4_That = Resource("crminf:J4", "that", class_uri="owl:Property")
    J5_Holds_To_Be = Resource("crminf:J5", "holds to be", class_uri="owl:Property")
