# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class CRMSCI(Ontology):

    def __init__(self) -> None:
        super().__init__('CRMsci version 2.0', 'crmsci', 'http://www.cidoc-crm.org/cidoc-crm/CRMsci/')

    # Classes
    S19_Encounter_Event = Resource("crmsci:S19", "Encounter Event", class_uri="owl:Class")
    S4_Observation = Resource("crmsci:S4", "Observation", class_uri="owl:Class")
    S9_Property_Type = Resource("crmsci:S9", "Property Type", class_uri="owl:Class")
    S1_Matter_Removal = Resource("crmsci:S1", "Matter Removal", class_uri="owl:Class")
    S10_Material_Substantial = Resource("crmsci:S10", "Material Substantial", class_uri="owl:Class")
    S15_Observable_Entity = Resource("crmsci:S15", "Observable Entity", class_uri="owl:Class")

    # Properties
    O19_Encountered_Object = Resource("crmsci:O19", "encountered object", class_uri="owl:Property")
    O9_Observed_Property_Type = Resource("crmsci:O9", "observed property type", class_uri="owl:Property")
    O1_Diminished = Resource("crmsci:O1", "diminished", class_uri="owl:Property")
    O12_Has_Dimension = Resource("crmsci:O12", "has dimension", class_uri="owl:Property")
    O15_Occupied = Resource("crmsci:O15", "occupied", class_uri="owl:Property")
    O25_Contains = Resource("crmsci:O25", "contains", class_uri="owl:Property")
