# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class CRMTEX(Ontology):

    def __init__(self) -> None:
        super().__init__('CRMtex version 2.0', 'crmtex', 'http://www.cidoc-crm.org/extensions/crmtex/')

    # Classes
    TX1_Written_Text = Resource("crmtex:TX1", "Written Text", class_uri="owl:Class")
    TX2_Writing = Resource("crmtex:TX2", "Writing", class_uri="owl:Class")
    TX3_Writing_System = Resource("crmtex:TX3", "Writing System", class_uri="owl:Class")
    TX5_Text_Recognition = Resource("crmtex:TX5", "Text Recognition", class_uri="owl:Class")
    TX6_Transliteration = Resource("crmtex:TX6", "Transliteration", class_uri="owl:Class")
    TX12_Grapheme_Sequence = Resource("crmtex:TX12", "Grapheme Sequence", class_uri="owl:Class")

    # Properties
    TXP1_Used_Writing_System = Resource("crmtex:TXP1", "used writing system", class_uri="owl:Property")
    TXP5_Wrote = Resource("crmtex:TXP5", "wrote", class_uri="owl:Property")
    TXP6_Encodes = Resource("crmtex:TXP6", "encodes", class_uri="owl:Property")
    TXP10_Deciphered_Text = Resource("crmtex:TXP10", "deciphered text", class_uri="owl:Property")
    TXP11_Transcribed = Resource("crmtex:TXP11", "transcribed", class_uri="owl:Property")
    TXP15_Recorded_Correspondence = Resource("crmtex:TXP15", "recorded correspondence", class_uri="owl:Property")
