# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class GEOV(Ontology):

    def __init__(self) -> None:
        super().__init__('Geovistory (ongoing)', 'geov', 'https://ontome.net/ns/geovistory/')

    # Classes
    C12_Argument = Resource("geov:C12", "Argument", class_uri="owl:Class")
    C1_Digital = Resource("geov:C1", "[Geovistory] Digital", class_uri="owl:Class")
    C2_Chunk = Resource("geov:C2", "Chunk", class_uri="owl:Class")
    C3_Spot = Resource("geov:C3", "Spot", class_uri="owl:Class")
    C13_Argument_S_Method = Resource("geov:C13", "Argument's method", class_uri="owl:Class")
    C4_Web_Request = Resource("geov:C4", "Web Request", class_uri="owl:Class")
    C6_Expression_Fragment = Resource("geov:C6", "Expression fragment", class_uri="owl:Class")
    C7_Cell = Resource("geov:C7", "Cell", class_uri="owl:Class")
    C8_Web_Request_Type = Resource("geov:C8", "Web request type", class_uri="owl:Class")
    C9_Tag = Resource("geov:C9", "Tag", class_uri="owl:Class")
    C11_Reference = Resource("geov:C11", "Reference", class_uri="owl:Class")
    C14_Uniform_Resource_Locator__Url = Resource("geov:C14", "Uniform Resource Locator (URL)", class_uri="owl:Class")
    C15_Short_Title = Resource("geov:C15", "Short title", class_uri="owl:Class")
    C16_Text = Resource("geov:C16", "Text", class_uri="owl:Class")
    C17_Manifestation_Singleton_Appellation_Type = Resource("geov:C17", "Manifestation Singleton Appellation Type", class_uri="owl:Class")
    C10_Namespace = Resource("geov:C10", "Namespace", class_uri="owl:Class")
    C18_Table = Resource("geov:C18", "Table", class_uri="owl:Class")
    C19_Definition = Resource("geov:C19", "Definition", class_uri="owl:Class")
    C20_Comment = Resource("geov:C20", "Comment", class_uri="owl:Class")
    C23_Text_Type = Resource("geov:C23", "Text type", class_uri="owl:Class")
    C24_Comment_Type = Resource("geov:C24", "Comment type", class_uri="owl:Class")
    C26_Annotation_In_Text = Resource("geov:C26", "Annotation in Text", class_uri="owl:Class")
    C27_Annotation_In_Table = Resource("geov:C27", "Annotation in Table", class_uri="owl:Class")
    C28_Mentioning = Resource("geov:C28", "Mentioning", class_uri="owl:Class")
    C29_Table_Value = Resource("geov:C29", "Table Value", class_uri="owl:Class")
    C31_Mentioning_In_Table = Resource("geov:C31", "Mentioning in Table", class_uri="owl:Class")

    # Properties
    P15_Has_Argument_Method = Resource("geov:P15", "has argument method", class_uri="owl:Property")
    P4_Is_Server_Response_To_Request = Resource("geov:P4", "is server response to request", class_uri="owl:Property")
    P5_Has_Carrier_Provided_By = Resource("geov:P5", "has carrier provided by", class_uri="owl:Property")
    P8_Has_Web_Request_Type = Resource("geov:P8", "has web request type", class_uri="owl:Property")
    P12_Tagged_By = Resource("geov:P12", "tagged by", class_uri="owl:Property")
    P13_Should_Be_Merged_With = Resource("geov:P13", "should be merged with", class_uri="owl:Property")
    P16_Has_Web_Address = Resource("geov:P16", "has web address", class_uri="owl:Property")
    P17_Has_Short_Title = Resource("geov:P17", "has short title", class_uri="owl:Property")
    P14_Belongs_To = Resource("geov:P14", "belongs to", class_uri="owl:Property")
    P1_Is_Reproduction_Of = Resource("geov:P1", "is reproduction of", class_uri="owl:Property")
    P9_Refers_To = Resource("geov:P9", "refers to", class_uri="owl:Property")
    P18_Has_Definition = Resource("geov:P18", "has definition", class_uri="owl:Property")
    P19_Has_Comment = Resource("geov:P19", "has comment", class_uri="owl:Property")
    P20_Has_Value_Version = Resource("geov:P20", "has value version", class_uri="owl:Property")
    P21_Has_Text_Type = Resource("geov:P21", "has text type", class_uri="owl:Property")
    P22_Has_Comment_Type = Resource("geov:P22", "has comment type", class_uri="owl:Property")
    P23_Is_Annotated_In = Resource("geov:P23", "is annotated in", class_uri="owl:Property")
    P24_At_Position = Resource("geov:P24", "at position", class_uri="owl:Property")
    P25_Annotated_Entity = Resource("geov:P25", "annotated entity", class_uri="owl:Property")
    P26_Mentions = Resource("geov:P26", "mentions", class_uri="owl:Property")
    P27_Is_Mentioned_In = Resource("geov:P27", "is mentioned in", class_uri="owl:Property")
    P28_At_Position = Resource("geov:P28", "at position", class_uri="owl:Property")
    P29_Has_Value = Resource("geov:P29", "has value", class_uri="owl:Property")
    P30_Is_About = Resource("geov:P30", "is about", class_uri="owl:Property")
    P31_Has_Mentioning_Content = Resource("geov:P31", "has mentioning content", class_uri="owl:Property")
