# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class HISARC(Ontology):

    def __init__(self) -> None:
        super().__init__('HisArc-RDF ongoing', 'hisarc', 'https://ontome.net/ns/hisarc-rdf/')

    # Classes
    C2_Physical_Man_Made_Thing_Type = Resource("hisarc:C2", "Physical Man-Made Thing Type", class_uri="owl:Class")

    # Properties
    P1_Is_Physical_Man_Made_Thing_Type_Of = Resource("hisarc:P1", "is physical man-made thing type of", class_uri="owl:Property")
