# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class ONTOMESAND(Ontology):

    def __init__(self) -> None:
        super().__init__('OntoME sandbox Test namespace ongoing', 'ontomesand', 'https://ontome.net/ns/test-namespace/')

    # Classes
    Building_Building = Resource("ontomesand:Building", "Building", class_uri="owl:Class")
    C9_Glacière = Resource("ontomesand:C9", "Glacière", class_uri="owl:Class")

    # Properties
    P8_Comprend = Resource("ontomesand:P8", "comprend", class_uri="owl:Property")
