# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class PRCT(Ontology):

    def __init__(self) -> None:
        super().__init__('Processetti ongoing', 'prct', 'https://ontome.net/ns/processetti/')

    # Classes
    C1_Pre_Matrimonial_Enquiry = Resource("prct:C1", "Pre-matrimonial enquiry", class_uri="owl:Class")
    C2_Marital_Status = Resource("prct:C2", "Marital status", class_uri="owl:Class")
    C3_Pre_Matrimonial_Enquiry_Motivation_Type = Resource("prct:C3", "Pre-matrimonial enquiry motivation type", class_uri="owl:Class")
    C4_Account_Of_A_Journey_Or_Stay = Resource("prct:C4", "Account of a journey or stay", class_uri="owl:Class")
    C5_Concept_Referred_To_In_A_Journey_S_Or_Stay_S_Account = Resource("prct:C5", "Concept referred to in a journey's or stay's account", class_uri="owl:Class")
    C6_Frequency_Class = Resource("prct:C6", "Frequency class", class_uri="owl:Class")

    # Properties
    P1_The_Investigation_Concerns = Resource("prct:P1", "the investigation concerns", class_uri="owl:Property")
    P2_Is_Requested_As_A_Witness = Resource("prct:P2", "is requested as a witness", class_uri="owl:Property")
    P3_Is_Documented_In = Resource("prct:P3", "is documented in", class_uri="owl:Property")
    P4_Has_Motivation = Resource("prct:P4", "has motivation", class_uri="owl:Property")
    P5_Has_Motivation_Type = Resource("prct:P5", "has motivation type", class_uri="owl:Property")
    P6_Has_Duration = Resource("prct:P6", "has duration", class_uri="owl:Property")
    P7_Mentions_Geographical_Place = Resource("prct:P7", "mentions geographical place", class_uri="owl:Property")
    P8_Concerns = Resource("prct:P8", "concerns", class_uri="owl:Property")
    P9_Has_Time_Lapse_Before_Account = Resource("prct:P9", "has time lapse before account", class_uri="owl:Property")
    P10_Refers_To = Resource("prct:P10", "refers to", class_uri="owl:Property")
    P11_Has_Frequency_Classification = Resource("prct:P11", "has frequency classification", class_uri="owl:Property")
    P12_Has_As_A_Minimum_Duration = Resource("prct:P12", "has as a minimum duration", class_uri="owl:Property")
    P13_Has_As_A_Maximum_Duration = Resource("prct:P13", "has as a maximum duration", class_uri="owl:Property")
    P14_Has_Time_Lapse_Of_Last_Journey_Before_Account = Resource("prct:P14", "has time lapse of last journey before account", class_uri="owl:Property")
    P15_Has_Marital_Status = Resource("prct:P15", "has marital status", class_uri="owl:Property")
    P16_Has_Intermediary = Resource("prct:P16", "has intermediary", class_uri="owl:Property")
