# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class SDH_ACT(Ontology):

    def __init__(self) -> None:
        super().__init__('SDHSS Extension - Human Activity ongoing', 'sdh-act', 'https://sdhss.org/ontology/human-activity/')

    # Classes
    C1_Actor_S_Movement_Or_Journey = Resource("sdh-act:C1", "Actor's Movement or Journey", class_uri="owl:Class")
    C2_Stopover = Resource("sdh-act:C2", "Stopover", class_uri="owl:Class")
    C3_Stopover_Type = Resource("sdh-act:C3", "Stopover Type", class_uri="owl:Class")
    C4_Actor_S_Movement_Or_Journey_Type = Resource("sdh-act:C4", "Actor's Movement or Journey Type", class_uri="owl:Class")
    C5_Carrier_S_Journey = Resource("sdh-act:C5", "Carrier's Journey", class_uri="owl:Class")
    C6_Carrier_S_Journey_Type = Resource("sdh-act:C6", "Carrier's Journey Type", class_uri="owl:Class")
    C7_Actor_S_Coerced_Trip = Resource("sdh-act:C7", "Actor's Coerced Trip", class_uri="owl:Class")
    C8_Actor_S_Coerced_Trip_Type = Resource("sdh-act:C8", "Actor's Coerced Trip Type", class_uri="owl:Class")

    # Properties
    P1_Is_Movement_Of = Resource("sdh-act:P1", "is movement of", class_uri="owl:Property")
    P2_Has_Movement_Identifying_Type = Resource("sdh-act:P2", "has movement identifying type", class_uri="owl:Property")
    P3_Has_Stopover_Identifying_Type = Resource("sdh-act:P3", "has stopover identifying type", class_uri="owl:Property")
    P4_Is_Journey_Of = Resource("sdh-act:P4", "is journey of", class_uri="owl:Property")
    P5_Has_Carrier_S_Journey_Identifying_Type = Resource("sdh-act:P5", "has carrier's journey identifying type", class_uri="owl:Property")
    P6_Is_Coerced_Displacement_Of = Resource("sdh-act:P6", "is coerced displacement of", class_uri="owl:Property")
    P7_Has_Actor_S_Coerced_Trip_Identifying_Type = Resource("sdh-act:P7", "has actor's coerced trip identifying type", class_uri="owl:Property")
    P8_Is_Continuation_Of = Resource("sdh-act:P8", "is continuation of", class_uri="owl:Property")
