# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class SILKNOW(Ontology):

    def __init__(self) -> None:
        super().__init__('SILKNOW 0.1', 'silknow', 'https://ontome.net/ns/silknow/')

    # Classes
    T1_Weaving = Resource("silknow:T1", "Weaving", class_uri="owl:Class")
    T2_Entering__Deprecated = Resource("silknow:T2", "Entering (Deprecated)", class_uri="owl:Class")
    T3_Spinning__Deprecated = Resource("silknow:T3", "Spinning (deprecated)", class_uri="owl:Class")
    T4_Throwing__Deprecated = Resource("silknow:T4", "Throwing (deprecated)", class_uri="owl:Class")
    T5_Warping__Deprecated = Resource("silknow:T5", "Warping (deprecated)", class_uri="owl:Class")
    T6_Loom = Resource("silknow:T6", "Loom", class_uri="owl:Class")
    T7_Fabric = Resource("silknow:T7", "Fabric", class_uri="owl:Class")
    T8_Part_Weaving = Resource("silknow:T8", "Part Weaving", class_uri="owl:Class")
    T9_Pattern_Zone = Resource("silknow:T9", "Pattern Zone", class_uri="owl:Class")
    T10_Ground = Resource("silknow:T10", "Ground", class_uri="owl:Class")
    T11_Style = Resource("silknow:T11", "Style", class_uri="owl:Class")
    T12_Selvedge__Deprecated = Resource("silknow:T12", "Selvedge (deprecated)", class_uri="owl:Class")
    T13_Style_Assignment = Resource("silknow:T13", "Style Assignment", class_uri="owl:Class")
    T14_Starting_Border__Deprecated = Resource("silknow:T14", "Starting Border (deprecated)", class_uri="owl:Class")
    T15_Yarn = Resource("silknow:T15", "Yarn", class_uri="owl:Class")
    T16_Warp = Resource("silknow:T16", "Warp", class_uri="owl:Class")
    T17_Weft = Resource("silknow:T17", "Weft", class_uri="owl:Class")
    T18_Motif = Resource("silknow:T18", "Motif", class_uri="owl:Class")
    T19_Object_Domain_Assignment = Resource("silknow:T19", "Object Domain Assignment", class_uri="owl:Class")
    T20_Twist = Resource("silknow:T20", "Twist", class_uri="owl:Class")
    T21_Weave = Resource("silknow:T21", "Weave", class_uri="owl:Class")
    T23_Fabric_Type = Resource("silknow:T23", "Fabric Type", class_uri="owl:Class")
    T24_Pattern_Unit = Resource("silknow:T24", "Pattern Unit", class_uri="owl:Class")
    T25_Weaving_Technique = Resource("silknow:T25", "Weaving Technique", class_uri="owl:Class")
    T26_Loom_Type = Resource("silknow:T26", "Loom Type", class_uri="owl:Class")
    T28_Yarn_Type = Resource("silknow:T28", "Yarn Type", class_uri="owl:Class")
    T29_Twist_Type = Resource("silknow:T29", "Twist Type", class_uri="owl:Class")
    T30_Warp_Type = Resource("silknow:T30", "Warp Type", class_uri="owl:Class")
    T31_Warping_Type__Deprecated = Resource("silknow:T31", "Warping Type (deprecated)", class_uri="owl:Class")
    T32_Weave_Type = Resource("silknow:T32", "Weave Type", class_uri="owl:Class")
    T33_Weft_Type = Resource("silknow:T33", "Weft Type", class_uri="owl:Class")
    T34_Motif_Type = Resource("silknow:T34", "Motif Type", class_uri="owl:Class")
    T35_Object_Type_Assignment = Resource("silknow:T35", "Object Type Assignment", class_uri="owl:Class")
    T36_Embroidery = Resource("silknow:T36", "Embroidery", class_uri="owl:Class")
    T37_Galloon = Resource("silknow:T37", "Galloon", class_uri="owl:Class")
    T38_Lining = Resource("silknow:T38", "Lining", class_uri="owl:Class")

    # Properties
    L1_Assigned_Object_Type = Resource("silknow:L1", "assigned object type", class_uri="owl:Property")
    L3_Has_Yarn_Type = Resource("silknow:L3", "has yarn type", class_uri="owl:Property")
    L4_Assigned_Domain_Type = Resource("silknow:L4", "assigned domain type", class_uri="owl:Property")
    L5_Has_Twist_Type = Resource("silknow:L5", "has twist type", class_uri="owl:Property")
    L6_Has_Warp_Type = Resource("silknow:L6", "has warp type", class_uri="owl:Property")
    L7_Used_Warp = Resource("silknow:L7", "used warp", class_uri="owl:Property")
    L8_Used_Weave = Resource("silknow:L8", "used weave", class_uri="owl:Property")
    L9_Used_Weft = Resource("silknow:L9", "used weft", class_uri="owl:Property")
    L10_Used_Yarn = Resource("silknow:L10", "used yarn", class_uri="owl:Property")
    L11_Has_Weave_Type = Resource("silknow:L11", "has weave type", class_uri="owl:Property")
    L12_Has_Motif_Type = Resource("silknow:L12", "has motif type", class_uri="owl:Property")
    L13_Has_Warping_Type_Deprecated = Resource("silknow:L13", "has warping type (deprecated)", class_uri="owl:Property")
    L14_Used_Specific_Weaving_Technique = Resource("silknow:L14", "used specific weaving technique", class_uri="owl:Property")
    L15_Has_Weft_Type = Resource("silknow:L15", "has weft type", class_uri="owl:Property")
