# File automatically generated by python script, from OntoMe API
# Script located at: graphly/scripts/ontologies.ipynb

from graphly.schema.ontology import Ontology
from graphly.schema.resource import Resource

class SYM(Ontology):

    def __init__(self) -> None:
        super().__init__('symogih.org ontology v.1.3 ongoing', 'sym', 'https://ontome.net/ns/symogih/')

    # Classes
    TyIn14_Naissance = Resource("sym:TyIn14", "Naissance", class_uri="owl:Class")
    TyIn26_Décès = Resource("sym:TyIn26", "Décès", class_uri="owl:Class")
    TyIn36_Localisation = Resource("sym:TyIn36", "Localisation", class_uri="owl:Class")
    TyIn11_Obtenir_Une_Qualité = Resource("sym:TyIn11", "Obtenir une qualité", class_uri="owl:Class")
    TyIn145_Passage_D_Un_Examen = Resource("sym:TyIn145", "Passage d'un examen", class_uri="owl:Class")
    TyIn149_Suspension_D_Activité = Resource("sym:TyIn149", "Suspension d'activité", class_uri="owl:Class")
    TyIn30_Création_D_Un_Acteur_Collectif = Resource("sym:TyIn30", "Création d'un acteur collectif", class_uri="owl:Class")

    # Properties
